### ISSUE TITLE
electron-builderでビルドした時にCannot cleanupのエラーが出る

### ISSUE THREAD

**Issue by kPherox** [cutls/TheDesk#54]
ビルドログで
```
  • Cannot detect repository by .git/config. Please specify "repository" in the package.json (https://docs.npmjs.com/files/package.json#repository).
Please see https://electron.build/configuration/publish
```
とあるので
```
"repository": "https://github.com/cutls/TheDesk",
```
をpackage.jsonに追加すれば治りそうです

stack trace
```
TypeError: Cannot read property 'provider' of null
    at /Users/kPherox/Developer/TheDesk/app/node_modules/app-builder-lib/src/publish/updateInfoBuilder.ts:110:44
From previous event:
    at _createUpdateInfoTasks (/Users/kPherox/Developer/TheDesk/app/node_modules/app-builder-lib/out/publish/updateInfoBuilder.js:251:33)
    at createUpdateInfoTasks (/Users/kPherox/Developer/TheDesk/app/node_modules/app-builder-lib/out/publish/updateInfoBuilder.js:176:33)
    at /Users/kPherox/Developer/TheDesk/app/node_modules/app-builder-lib/src/publish/PublishManager.ts:186:32
From previous event:
    at PublishManager.artifactCreatedWithoutExplicitPublishConfig (/Users/kPherox/Developer/TheDesk/app/node_modules/app-builder-lib/src/publish/PublishManager.ts:155:83)
    at EventEmitter.PublishManager.packager.artifactCreated.event (/Users/kPherox/Developer/TheDesk/app/node_modules/app-builder-lib/src/publish/PublishManager.ts:110:39)
    at EventEmitter.emit (events.js:187:15)
    at Packager.dispatchArtifactCreated (/Users/kPherox/Developer/TheDesk/app/node_modules/app-builder-lib/src/packager.ts:276:23)
    at /Users/kPherox/Developer/TheDesk/app/node_modules/app-builder-lib/src/packager.ts:280:10
    at Generator.next (<anonymous>)
From previous event:
    at Packager.callArtifactBuildCompleted (/Users/kPherox/Developer/TheDesk/app/node_modules/app-builder-lib/src/packager.ts:279:58)
    at /Users/kPherox/Developer/TheDesk/app/node_modules/app-builder-lib/src/targets/ArchiveTarget.ts:69:25
    at Generator.next (<anonymous>)
From previous event:
    at ArchiveTarget.build (/Users/kPherox/Developer/TheDesk/app/node_modules/app-builder-lib/src/targets/ArchiveTarget.ts:16:44)
    at Function.buildAsyncTargets (/Users/kPherox/Developer/TheDesk/app/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at MacPackager.packageInDistributableFormat (/Users/kPherox/Developer/TheDesk/app/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at nonMasPromise.then.then (/Users/kPherox/Developer/TheDesk/app/node_modules/app-builder-lib/src/macPackager.ts:90:26)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at /Users/kPherox/Developer/TheDesk/app/node_modules/app-builder-lib/src/macPackager.ts:90:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/kPherox/Developer/TheDesk/app/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Users/kPherox/Developer/TheDesk/app/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/kPherox/Developer/TheDesk/app/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/kPherox/Developer/TheDesk/app/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:159:5)
From previous event:
    at Packager.doBuild (/Users/kPherox/Developer/TheDesk/app/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/kPherox/Developer/TheDesk/app/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/kPherox/Developer/TheDesk/app/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/kPherox/Developer/TheDesk/app/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:145:20)
From previous event:
    at Packager._build (/Users/kPherox/Developer/TheDesk/app/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/kPherox/Developer/TheDesk/app/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Packager.build (/Users/kPherox/Developer/TheDesk/app/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/kPherox/Developer/TheDesk/app/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/kPherox/Developer/TheDesk/app/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/Users/kPherox/Developer/TheDesk/app/node_modules/electron-builder/src/cli/cli.ts:46:19)
```

**Comment by cutls** [comment]
修正コミットしました(コミット名に #54 入れたのになぜかうまくいかなかった(多分ブランチミス))

**Comment by kPherox** [comment]
masterがメインブランチなのでそこにマージされてようやく閉じられるみたいです。<s>#64になってますね</s>
