### ISSUE TITLE
macOS Ventura 13.3.1、Xcode 14.3でyarn installができない

### ISSUE THREAD

**Issue by toneji** [cutls/TheDesk#952]
macOS Ventura 13.3.1、Xcode 14.3、MacBook Pro 16inch(2019)で、TheDesk v24.1.2をyarn installするとエラーで終了します。

以下、ターミナルからコピーペーストします。

```
$ yarn install
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > babel-loader@9.1.2" has unmet peer dependency "webpack@>=5".
warning " > rollup-plugin-babel@4.4.0" has incorrect peer dependency "rollup@>=0.60.0 <3".
warning " > rollup-plugin-terser@7.0.2" has incorrect peer dependency "rollup@^2.0.0".
[4/4] 🔨  Building fresh packages...
$ run-s util:*
yarn run v1.22.19
$ node gitHash.js
/Users/haru/TheDesk/app/gitHash.js:17
    const response = await fetch(apiUrl)
                     ^

ReferenceError: fetch is not defined
    at createContributorsList (/Users/haru/TheDesk/app/gitHash.js:17:22)
    at Object.<anonymous> (/Users/haru/TheDesk/app/gitHash.js:9:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "util:hash" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

公式に行ってみたところ、macOS版には「build failing」のタグが付いていました。
もちろん、githubのサイトでも同じタグが。

現状では、macOSでbuildできないのでしょうか？
急ぎませんので、対応のほどよろしくお願いいたします。

**Comment by cutls** [comment]
何も考えずにfetch API(Node.js v18以降で対応)を使用していますね…
Node.jsをv18以降にアップデートすれば問題無いのですが、それも微妙なので修正を予定しています。
